### ISSUE TITLE
la4j library cannot be found

### ISSUE THREAD

**Issue by qubotong** [toggled/Hypervis#1]
In the Processing 3.5.4, the la4j library cannot be imported. Is that possible we provide this library in the sketchbook folder in our release?

**Comment by qubotong** [comment]
found it in the code. I am new to the Processing, it would be great if more instructions could be provided to people like me who do not have any background in Processing.

**Comment by toggled** [comment]
Hi,

I added instructions about installing external libraries/dependencies in README. Let me know if it is sufficient. 

Hypervis is meant for those without any background in Processing, but need to visualise hypergraphs , possibly without any need to do coding. So, thanks for your feedbacks. :)
